---
- name: Install MariaDB & mysql-python prereq
  apt: name={{ item }} update_cache=yes state=present
  loop: ["mariadb-server", "python3-pymysql"]

# MariaDB Configuration
- name: Sets the root password
  vars:
    mysql_root_password: MYSQL_ROOT_PASSWORD
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_host: localhost
    login_port: 3306
    login_user: root
    login_password: "{{ mysql_root_password }}"

    # login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: false
- name: Removes all anonymous user accounts
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: false
- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Creates App Database
  mysql_db:
    name: "{{ mysql_app_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create App MySQL user and grants access to App DB
  mysql_user:
    name: "{{ mysql_app_user }}"
    password: "{{ mysql_app_pass }}"
    priv: "{{ mysql_app_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
