---
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages:
  [
    "curl",
    "vim",
    "git",
    "ufw",
    "python3.9",
    "python3.9-venv",
    "python3-pip",
    "software-properties-common",
  ]
